# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

minl_cpp <- function(beta, psi, y1, y2, n1, n2, mu_beta, sigma_beta, mu_psi, sigma_psi) {
    .Call('_abtest_minl_cpp', PACKAGE = 'abtest', beta, psi, y1, y2, n1, n2, mu_beta, sigma_beta, mu_psi, sigma_psi)
}

apply_minl_cpp <- function(s, y1, y2, n1, n2, mu_beta, sigma_beta, mu_psi, sigma_psi) {
    .Call('_abtest_apply_minl_cpp', PACKAGE = 'abtest', s, y1, y2, n1, n2, mu_beta, sigma_beta, mu_psi, sigma_psi)
}

minlminus_cpp <- function(beta, xi, y1, y2, n1, n2, mu_beta, sigma_beta, mu_psi, sigma_psi) {
    .Call('_abtest_minlminus_cpp', PACKAGE = 'abtest', beta, xi, y1, y2, n1, n2, mu_beta, sigma_beta, mu_psi, sigma_psi)
}

apply_minlminus_cpp <- function(s, y1, y2, n1, n2, mu_beta, sigma_beta, mu_psi, sigma_psi) {
    .Call('_abtest_apply_minlminus_cpp', PACKAGE = 'abtest', s, y1, y2, n1, n2, mu_beta, sigma_beta, mu_psi, sigma_psi)
}

minlplus_cpp <- function(beta, xi, y1, y2, n1, n2, mu_beta, sigma_beta, mu_psi, sigma_psi) {
    .Call('_abtest_minlplus_cpp', PACKAGE = 'abtest', beta, xi, y1, y2, n1, n2, mu_beta, sigma_beta, mu_psi, sigma_psi)
}

apply_minlplus_cpp <- function(s, y1, y2, n1, n2, mu_beta, sigma_beta, mu_psi, sigma_psi) {
    .Call('_abtest_apply_minlplus_cpp', PACKAGE = 'abtest', s, y1, y2, n1, n2, mu_beta, sigma_beta, mu_psi, sigma_psi)
}

